### PR TITLE
Fix #62 No longer throws NPE in `GithubResolver`

### LINKED ISSUE #62: When using a public github repository not registred in bower on heruko an exception is thrown
Bower supports a structure like this:

"dependencies": {
    "my-assets": "https://github.com/myorg/my-assets.git#master"
}
But trying this with my repo being public:

bower {
    'my-assets'('1.0.1') {
        url '"https://github.com/myrepo/my-assets.git'
    }
}
Gives me this exception:

Caused by: java.io.FileNotFoundException: https://bower.herokuapp.com/packages/my-assets
        at com.craigburke.gradle.client.registry.bower.BowerRegistry.loadInfoFromRegistry(BowerRegistry.groovy:88)
        at com.craigburke.gradle.client.registry.core.AbstractRegistry$_setInfo_closure4.doCall(AbstractRegistry.groovy:146)
        at com.craigburke.gradle.client.registry.core.AbstractRegistry$_setInfo_closure4.doCall(AbstractRegistry.groovy)
(This is running on the latest 1.3.0-SNAPSHOT build locally)

### PR DESCRIPTION
**Pull request by sbglasius**
No longer throws FileNotFound in `BowerRegistry`

### CODE REVIEW

File: src/main/groovy/com/craigburke/gradle/client/registry/core/AbstractRegistry.groovy [hunk 1]
```diff
@@ -151,7 +151,7 @@ abstract class AbstractRegistry implements Registry {
                 infoFile.parentFile.mkdirs()
                 infoFile.text = new JsonBuilder(dependency.info).toPrettyString()
             }
-
+            dependency.info = dependency.info ?: [:]
```
Comment (sbglasius) [inline src/main/groovy/com/craigburke/gradle/client/registry/core/AbstractRegistry.groovy:154]: If `depencency.info` is null, then https://github.com/craigburke/client-dependencies-gradle/blob/master/src/main/groovy/com/craigburke/gradle/client/registry/bower/GithubResolver.groovy#L88 and https://github.com/craigburke/client-dependencies-gradle/blob/master/src/main/groovy/com/craigburke/gradle/client/registry/bower/GithubResolver.groovy#L92 will throw NPE's

**Comment by craigburke** [comment]
Very nice! LGTM!
